import type { PRD } from "@/lib/schemas/prd-schema";

/**
 * Formats a PRD object into a clean Markdown string
 * suitable for download or sharing with development teams
 */
export function formatPRDToMarkdown(prd: PRD): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${prd.overview.name}`);
  lines.push("");
  lines.push(`*${prd.overview.tagline}*`);
  lines.push("");

  // Overview
  lines.push("## Product Overview");
  lines.push("");
  lines.push(`**Problem Statement:** ${prd.overview.problemStatement}`);
  lines.push("");
  lines.push(`**Core Objective:** ${prd.overview.coreObjective}`);
  lines.push("");
  lines.push(`**Target Audience:** ${prd.overview.targetAudience}`);
  lines.push("");

  // Tech Stack
  lines.push("## Tech Stack");
  lines.push("");

  if (prd.techstack.frontend.length > 0) {
    lines.push("### Frontend");
    prd.techstack.frontend.forEach((tech) => lines.push(`- ${tech}`));
    lines.push("");
  }

  if (prd.techstack.backend.length > 0) {
    lines.push("### Backend");
    prd.techstack.backend.forEach((tech) => lines.push(`- ${tech}`));
    lines.push("");
  }

  if (prd.techstack.database.length > 0) {
    lines.push("### Database");
    prd.techstack.database.forEach((tech) => lines.push(`- ${tech}`));
    lines.push("");
  }

  if (prd.techstack.ai.length > 0) {
    lines.push("### AI");
    prd.techstack.ai.forEach((tech) => lines.push(`- ${tech}`));
    lines.push("");
  }

  if (prd.techstack.infrastructure.length > 0) {
    lines.push("### Infrastructure");
    prd.techstack.infrastructure.forEach((tech) => lines.push(`- ${tech}`));
    lines.push("");
  }

  // Core Features
  lines.push("## Core Features");
  lines.push("");

  prd.coreFeatures.forEach((feature) => {
    lines.push(`### ${feature.name}`);
    lines.push(
      `**Priority:** ${feature.priority} | **Status:** ${feature.status}`
    );
    lines.push("");
    lines.push(feature.description);
    lines.push("");
  });

  // Rules
  lines.push("## Rules & Guidelines");
  lines.push("");

  prd.rules.forEach((rule) => {
    lines.push(`### ${rule.category}`);
    lines.push(rule.content);
    lines.push("");
  });

  // Metadata
  lines.push("---");
  lines.push(`*Generated by VICO | Version: ${prd.version || "1.0.0"}*`);
  const dateStr = prd.createdAt
    ? new Date(prd.createdAt).toISOString()
    : new Date().toISOString();
  lines.push(`*Created: ${dateStr}*`);

  return lines.join("\n");
}